# @package _global_

# default debugging setup which runs for 100 steps â€“ a starting point for the other configs

defaults:
  - override /hydra: debug

num_steps: 100
num_validation_runs: 3

trainer:
  max_steps: ${num_steps}
  gpus: 0 # debuggers don't like gpus
  track_grad_norm: 2 # track gradient norm with loggers
  val_check_interval: ${floor_div:${num_steps}, ${num_validation_runs}}
  #  Available in newer version of PL
  #  detect_anomaly: true # raise exception if NaN or +/-inf is detected in any tensor

datamodule:
  num_workers: 0 # debuggers don't like multiprocessing
  pin_memory: False # disable gpu memory pin

# sets level of all command line loggers to 'DEBUG'
# https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
hydra:
  verbose: True

# config is already printed by hydra when `hydra/verbose: True`
print_config: False
