# @package _global_

# runs `num_steps` of training with `num_validation_runs` validation cycles
# uses the same (first) `num_batches` batches of the training dataloader for both training and validation

defaults:
  - default.yaml

trainer:
  max_steps: ${num_steps}
  overfit_batches: ${num_batches}
  val_check_interval: ${floor_div:${num_steps}, ${num_validation_runs}}

num_steps: 20000
num_batches: 5
num_validation_runs: 4000
